"""empty message

Revision ID: 037955eb5b3f
Revises: 7164ec107ff0
Create Date: 2022-01-24 19:51:17.546852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037955eb5b3f'
down_revision = '7164ec107ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
