"""empty message

Revision ID: 1c4f35f86511
Revises: f4b0d7d14663
Create Date: 2021-06-07 17:45:35.399243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4f35f86511'
down_revision = 'f4b0d7d14663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.add_column('telegram_users', sa.Column('message_id', sa.Integer(), nullable=True))
    op.add_column('telegram_users', sa.Column('num_referals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'num_referals')
    op.drop_column('telegram_users', 'message_id')
    op.drop_column('telegram_users', 'chapter_id')
    # ### end Alembic commands ###
