"""empty message

Revision ID: 2832a9d50342
Revises: 04418bc3856a
Create Date: 2021-06-16 10:50:11.354380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2832a9d50342'
down_revision = '04418bc3856a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('telegram_users', sa.Column('email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'email')
    op.drop_table('patrons')
    # ### end Alembic commands ###
