"""empty message

Revision ID: 3305ddd4c403
Revises: 1c4f35f86511
Create Date: 2021-06-07 23:26:15.280481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3305ddd4c403'
down_revision = '1c4f35f86511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=True),
    sa.Column('uid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
