"""empty message

Revision ID: 692dd99611f7
Revises: bf9adbdb50a4
Create Date: 2022-01-24 21:29:37.458590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692dd99611f7'
down_revision = 'bf9adbdb50a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('tg_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'tg_id')
    # ### end Alembic commands ###
