"""empty message

Revision ID: 73ffa4dd8300
Revises: 2832a9d50342
Create Date: 2022-01-24 16:56:03.498161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ffa4dd8300'
down_revision = '2832a9d50342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('link', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('next_msg', sa.Text(), nullable=True),
    sa.Column('wait_reaction_id', sa.Integer(), nullable=True),
    sa.Column('referal_block', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_msg'], ['messages.link'], ),
    sa.ForeignKeyConstraint(['wait_reaction_id'], ['wait_reactions.id'], ),
    sa.PrimaryKeyConstraint('link'),
    sa.UniqueConstraint('link')
    )
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parrent_message_link', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('next_message_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['next_message_link'], ['messages.link'], ),
    sa.ForeignKeyConstraint(['parrent_message_link'], ['messages.link'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('media', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    op.add_column('media', sa.Column('content_type', sa.Text(), nullable=True))
    op.add_column('media', sa.Column('parrent_message_link', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'media', 'messages', ['parrent_message_link'], ['link'])
    op.drop_column('media', 'uid')
    op.drop_column('media', 'file_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('uid', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'parrent_message_link')
    op.drop_column('media', 'content_type')
    op.drop_column('media', 'file_data')
    op.drop_table('buttons')
    op.drop_table('messages')
    # ### end Alembic commands ###
