"""empty message

Revision ID: bf9adbdb50a4
Revises: 037955eb5b3f
Create Date: 2022-01-24 21:26:52.920030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9adbdb50a4'
down_revision = '037955eb5b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'content_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('content_type', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
